def nacenck(first='2020-01-01', second='2020-10-02'):
    test = f'''

    SELECT
     NUMBERS.NUM AS "NUM",
     GS.SHIFTDATE AS "SHIFTDATE",
     BALANCE.NAME AS "NAME",
     BALANCE.CHECKCNT AS "CHECKCNT",
     BALANCE.B_SUM AS "B_SUM"

    FROM GLOBALSHIFTS GS
    INNER JOIN (

     SELECT 6 AS NUM

     ) NUMBERS ON (1 = 1)
    LEFT JOIN 
    (




     (
    SELECT DISTINCT
      CASE WHEN SUM(DISCPARTS.SUM)>0 THEN 
       CASE WHEN (CASE WHEN DISCPARTS.SUM>0 THEN SQLCONSTS00.NAME + EV.USERMNAME ELSE SQLCONSTS01.NAME + EV.USERMNAME END)  --30  --31
       IS NULL THEN 5 ELSE 4 END
      ELSE
       CASE WHEN (CASE WHEN DISCPARTS.SUM>0 THEN SQLCONSTS00.NAME + EV.USERMNAME ELSE SQLCONSTS01.NAME + EV.USERMNAME END)  --30  --31
       IS NULL THEN 7 ELSE 6 END END AS "NUM",                                                             
      ISNULL((CASE WHEN DISCPARTS.SUM>0 THEN SQLCONSTS00.NAME + EV.USERMNAME ELSE SQLCONSTS01.NAME + EV.USERMNAME END),  --30  --31 
       CASE WHEN SUM(DISCPARTS.SUM) > 0 THEN max(SQLCONSTS02.NAME) ELSE max(SQLCONSTS03.NAME) END) AS "NAME",    --32  --33        
      COUNT(distinct PCH.GLOBALIDENT) AS "CHECKCNT",
      SUM(DISCPARTS.SUM) AS "B_SUM",
      NULL AS "COST",

      O.ICOMMONSHIFT AS "SHIFTNUM",
      O.UOT AS "UOT",
      O.MIDSERVER AS "MIDSERVER"
     FROM DISCPARTS
     JOIN PayBindings PayBindings00
      ON (PayBindings00.Visit = DiscParts.Visit) AND (PayBindings00.MidServer = DiscParts.MidServer) AND (PayBindings00.UNI = DiscParts.BindingUNI)
     JOIN CurrLines CurrLines00
      ON (CurrLines00.Visit = PayBindings00.Visit) AND (CurrLines00.MidServer = PayBindings00.MidServer) AND (CurrLines00.UNI = PayBindings00.CurrUNI)
     JOIN DishDiscounts DD
      ON (DD.Visit = DiscParts.Visit) AND (DD.MidServer = DiscParts.MidServer) AND (DD.UNI = DiscParts.DiscLineUNI) AND DD.ISCHARGE=0
     JOIN OrderSessions OrderSessions00
      ON (OrderSessions00.Visit = DD.Visit) AND (OrderSessions00.MidServer = DD.MidServer) AND (OrderSessions00.UNI = DD.SessionUNI)
     JOIN Orders O
      ON (O.Visit = OrderSessions00.Visit) AND (O.MidServer = OrderSessions00.MidServer) AND (O.IdentInVisit = OrderSessions00.OrderIdent)
     JOIN GLOBALSHIFTS GLOBALSHIFTS00
      ON (GLOBALSHIFTS00.MidServer = O.MidServer) AND (GLOBALSHIFTS00.ShiftNum = O.iCommonShift) AND GLOBALSHIFTS00.STATUS = 3
     LEFT JOIN SQLCONSTS SQLCONSTS00 ON SQLCONSTS00.SIFR=30
     LEFT JOIN SQLCONSTS SQLCONSTS01 ON SQLCONSTS01.SIFR=31
     LEFT JOIN SQLCONSTS SQLCONSTS02 ON SQLCONSTS02.SIFR=32
     LEFT JOIN SQLCONSTS SQLCONSTS03 ON SQLCONSTS03.SIFR=33
     JOIN PrintChecks PCH
      ON (PCH.Visit = CurrLines00.Visit) AND (PCH.MidServer = CurrLines00.MidServer) AND (PCH.UNI = CurrLines00.CheckUNI)  AND PCH.STATE=6
     LEFT JOIN TRK7ENUMSVALUES EV ON EV.ENUMNAME ='TChargeSource' AND DD.CHARGESOURCE = EV.ENUMDATA
     LEFT JOIN DISCOUNTS DISCOUNTS00
      ON (DISCOUNTS00.SIFR = DD.Sifr)
     where (DiscParts."NONZERODISC" = 1)
     GROUP BY
      O.ICOMMONSHIFT,O.UOT,O.MIDSERVER, CASE WHEN DISCPARTS.SUM>0 THEN 1 ELSE 0 END,
      (CASE WHEN DISCPARTS.SUM>0 THEN SQLCONSTS00.NAME + EV.USERMNAME ELSE SQLCONSTS01.NAME + EV.USERMNAME END) 

     WITH ROLLUP
     HAVING O.ICOMMONSHIFT IS NOT NULL
      AND O.UOT IS NOT NULL
      AND O.MIDSERVER IS NOT NULL
      AND CASE WHEN DISCPARTS.SUM>0 THEN 1 ELSE 0 END IS NOT NULL
     )
    ) BALANCE ON (NUMBERS.NUM = BALANCE.NUM AND GS.SHIFTNUM = BALANCE.SHIFTNUM AND GS.MIDSERVER = BALANCE.MIDSERVER) 
    LEFT JOIN UNCHANGEABLEORDERTYPES UOT ON (UOT.SIFR = BALANCE.UOT)

    LEFT JOIN CASHGROUPS CG ON (CG.SIFR = BALANCE.MIDSERVER)
    LEFT JOIN RESTAURANTS R ON R.SIFR = CG.RESTAURANT

    WHERE (GS.STATUS = 3 OR BALANCE.NUM = 10 OR BALANCE.NUM = 11)
     AND NOT((NUMBERS.NUM = 0 OR NUMBERS.NUM = 4 OR NUMBERS.NUM = 6)
             AND BALANCE.NAME IS NULL) AND "SHIFTDATE" >= '{first}' and "SHIFTDATE" <= '{second}'



    '''
    return test